export default [{
        id: 1,
        name: 'Standing Hamstring Kick',
        sets: 1,
        repeat: 15,
    },
    {
        id: 2,
        name: 'Single Leg RDL',
        sets: 1,
        repeat: 10,
    },
    {
        id: 3,
        name: 'Standing Toe Reach',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 4,
        name: 'Elephant Walk Stretch',
        sets: 1,
        repeat: 30,
    },
    {
        id: 5,
        name: 'Standing Good Morning',
        sets: 1,
        repeat: 30,
    },
    {
        id: 6,
        name: 'Seated Single Leg Hamstring Stretch',
        sets: 2,
        bySide: true,
        durationSec: 30,
    },
    {
        id: 7,
        name: 'Pilates Spine Stretch',
        sets: 1,
        repeat: 10,
    },
    {
        id: 8,
        name: 'Sit and Reach',
        sets: 1,
        durationSec: 30,
    },
    {
        id: 9,
        name: 'Pancake Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 10,
        name: 'ATG Split Squat',
        sets: 1,
        repeat: 10,
    },
    {
        id: 11,
        name: 'Elevated Pidgeon Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 12,
        name: 'Wide Stance Squats',
        sets: 1,
        repeat: 10,
    },
    {
        id: 13,
        name: 'Runners Lunge',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 14,
        name: 'Butterfly Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 15,
        name: '90/90 Hip Switch',
        sets: 1,
        repeat: 10,
    },
    {
        id: 16,
        name: 'Seated Good Mornings',
        sets: 1,
        repeat: 10,
    },
    {
        id: 17,
        name: 'Figure 4 Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 18,
        name: 'Kneeling Hip Flexor Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 19,
        name: 'Crossbody Arm Swings',
        sets: 1,
        repeat: 20,
    },
    {
        id: 20,
        name: 'Chair Dips',
        sets: 1,
        repeat: 10,
    },
    {
        id: 21,
        name: 'Dip Hold',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 22,
        name: 'Box Shoulder Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 23,
        name: 'Arm Circles',
        sets: 1,
        repeat: 20,
    },
    {
        id: 24,
        name: 'Chest Pulses',
        sets: 1,
        repeat: 20,
    },
    {
        id: 25,
        name: 'behind-theback Biceps Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 26,
        name: 'Door Frame Chest Stretch',
        sets: 3,
        durationSec: 30,
    },
    {
        id: 27,
        name: 'Standing Side Reach',
        sets: 1,
        repeat: 10,
    },
    {
        id: 28,
        name: 'Cat Cow Stretch',
        sets: 1,
        repeat: 10,
    },
    {
        id: 29,
        name: 'Wall Angels',
        sets: 1,
        repeat: 10,
    },
    {
        id: 30,
        name: 'Shoulder Rolls',
        sets: 1,
        repeat: 10,
    },
    {
        id: 31,
        name: 'Pilates Ab Curl',
        sets: 1,
        repeat: 10,
    },
    {
        id: 32,
        name: 'Pilates Basic Back Extension',
        sets: 1,
        repeat: 10,
    },
    {
        id: 33,
        name: 'Cat Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 34,
        name: 'Cow Stretch',
        sets: 2,
        durationSec: 30,
    },
    {
        id: 35,
        name: 'Balancing Table Pose',
        sets: 2,
        durationSec: 30,
        bySide: true,
    },
    {
        id: 36,
        name: 'Planks',
        sets: 1,
        durationSec: 30,
    },
]